version: "3"

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - tomcat
    
  tomcat:
    image: ubuntu:18.04
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: $DB_USERNAME
      MYSQL_PORT: 3306
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: UserDB
    command: >
      bash -c "
      apt-get update &&
      apt-get install -y tomcat8 default-jdk mysql-client telnet &&
      /usr/share/tomcat8/bin/catalina.sh run"
    volumes:
      - ./target/dptweb-1.0.war:/usr/local/tomcat/webapps/myapp.war
      - ./tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
    depends_on:
      - mysql
  
  mysql:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASS
      MYSQL_DATABASE: UserDb
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_USER: $DB_USERNAME
    volumes:
      - mysql-data:/var/lib/mysql
      - table.sql:/docker-entrypoint-initdb.d
volumes:
  mysql-data:
  table.sql: