version: "3"

services:
  nginx:
    image: my-nginx
    ports:
      - "80:80"
    depends_on:
      - tomcat
    
  tomcat:
    image: my-tomcat
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql
      MYSQL_USER: $DB_USERNAME
      MYSQL_PORT: 3306
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: UserDB
    depends_on:
      - mysql
  
  mysql:
    image: my-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASS
      MYSQL_DATABASE: UserDb
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_USER: $DB_USERNAME

networks:
  default:
    driver: bridge